---
- name: mysubreddit1
  cycles:
    - feeds:
        - url: https://example.com/feed1.rss
          block: [ item1, item2 ]
        - url: https://example.com/feed2.rss
      check_interval: 3600
      flair: Flair
    - feeds:
        - url: https://example.com/feed3.rss
      check_interval: 7200
- name: mysubreddit2
  cycles:
    - feeds:
        - url: https://example.com/feed4.rss
          block: [ ]  # Same as not specifying
        - url: https://example.com/feed5.rss
      check_interval: 14400
